name: Deploy Backend API to VPS

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/**' # Thêm dòng này để khi cấu hình file YAML nó cũng tự trigger
  workflow_dispatch: # Bắt buộc nên có để hiện nút "Run workflow" chạy thủ công trên Github

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ket noi SSH vao VPS va Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/CinePhine/backend
            git reset --hard HEAD
            git pull origin dev
            npm install
            pm2 restart cinephine-api
