name: Deploy Backend API to VPS

on:
  push:
    branches:
      - dev # (Lưu ý: Nếu nhánh chính của bạn tên là 'master', hãy đổi chữ 'main' thành 'master')
    paths:
      - 'backend/**' # Bot chỉ chạy khi có file nào đó trong thư mục backend bị thay đổi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ket noi SSH vao VPS va Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/CinePhine/backend
            git pull origin dev
            npm install
            pm2 restart cinephine-api